### ISSUE TITLE
A spam message

### ISSUE THREAD

**Issue by WongIong** [Slimefun-Addon-Community/SoundMuffler#10]
[週四, 13. 1月 2022 08:25:26 CST WARN] Loaded class dev.j3fftw.soundmuffler.SoundMufflerListener from SoundMuffler vDEV - 23 (git 2030f464) which is not a depend, softdepend or loadbefore of this plugin.
[週四, 13. 1月 2022 08:25:26 CST ERROR] [SoundMuffler] Unhandled exception occured in onPacketSending(PacketEvent) for SoundMuffler
[週四, 13. 1月 2022 08:25:26 CST ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntitySound@16c3765f[
    a=net.minecraft.sounds.SoundEffect@6eb17ec8
    b=BLOCKS
    c=62166
    d=1.0
    e=1.0
  ]

**Comment by J3fftw1** [comment]
Do you have protocollib installed? Also please list down all versions

**Comment by WongIong** [comment]
Sure i have
![image](https://user-images.githubusercontent.com/36799194/149318128-f7eb7fc3-e103-4b07-a110-10d59f67bc30.png)
The chinese name is slimefun

**Comment by J3fftw1** [comment]
do you have protocollib installed?

**Comment by WongIong** [comment]
As i said, Sure i have 
![image](https://user-images.githubusercontent.com/36799194/149420282-874a1f21-38f6-425a-823f-e6b21a6cc193.png)

**Comment by J3fftw1** [comment]
Your protocollib version doesnt support 1.17
you will have to use 4.7.0
https://owo.whats-th.is/5WMQsnb.png

Can be downloaded here  https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0

**Comment by WongIong** [comment]
ok

**Comment by WongIong** [comment]
https://pastebin.com/R09spnY4
after a downgrade of protocollib, it has a new error

**Comment by WongIong** [comment]
@J3fftw1 
it is still happening
https://pastebin.com/WQxgbsbP
