### ISSUE TITLE
Hates 1.20.2, 3, and 4. Please update.

### ISSUE THREAD

**Issue by MagmaSlime123** [Slimefun-Addon-Community/SoundMuffler#11]
Title.

![2024-01-14_17 56 43](https://github.com/Slimefun-Addon-Community/SoundMuffler/assets/51277766/034e6c7d-2995-44e3-88b2-2c88bf87f21a)
![2024-01-14_17 56 45](https://github.com/Slimefun-Addon-Community/SoundMuffler/assets/51277766/4d60cd21-abdd-4d43-a333-2cc5b499cf28)

**Comment by WalshyDev** [comment]
What does "hates" mean? Errors? Things not working? Logs? Any info at all??

**Comment by MagmaSlime123** [comment]
Not sure why the plugin doesn't give a more clear error about ProtocolLib missing. Would be nice if that was added.
